language: emacs-lisp
sudo: false
cache:
  - directories:
      - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
env:
  - EMACS_VERSION=24.4
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26
  - EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  - emacs --version
install:
  - cask install
script:
  - cask exec ert-runner
notifications:
  slack:
    secure: b6Bm3bktPjSmqq/TWZQRHXZ8ju5fQpGNr2qIz2kSvpqcDL4ggM+cHT4ddnH5Oapf13v9aJWErcsjQ5GJMhqQvvVWY3p6r0g89Mt5UnMPHTEUiD/e5trjBxZumQpBKTnRqBuvmAimA547+L0cErXCPjrrmleEC3BdeRw0THLNOr3knbNJgT8VuMv0Saah9Jqc5LP0WpAwyk2E5Q6c5qVmj7gB6HYNdf8d9MMuwwU6qcnxYp/Zn+/eJ+kovvcIc+tneOWe+h1IgR3miUgxRX4+GkGvm57CmbyOKxswacmswmLAcDkIN4hb7JSUSRFPIyifJ+zYS+rkY2Sa7EgbQl0Hu3wa1BFAk336TKCf7RD88xgxhWZHWD4B82DWZvoMHg0OHxO7HCf7IrwY8qIzwGc5MrN9ubdUrar+17qrGGa46lLTxiYo8YweRkk4556IIoGLXO35uGvUjFqeLzb3ZsTXjAIJTimcq9VYbNujjxzZfi0aZ23KqcMb18D1/xvIic7+nCXSkZ1DlOdxhp59TlRZjQU8KrpUu8uwNjQQ67EdTqIZOR5eAmod7Ea0VIA9SFyOEZHWu4Rdlbg25tM/w3RcHUWtB1nY4O/lWRC2oNEOTmzQCfUplZP9k2KyUpk6ohJpZ0nvNZSOgkaZAo30jBWCSuvAePsgjcURlGfZEp0sC9Y=
